import type { Zoo } from "./types";

export const zoos: Zoo[] = [
  {
    id: "tennoji-zoo",
    name: "天王寺動物園",
    nameKana: "てんのうじどうぶつえん",
    prefecture: "osaka",
    address: "大阪府大阪市天王寺区茶臼山町1-108",
    lat: 34.6494,
    lon: 135.5063,
    openingHours: "9:30〜17:00（入園は16:00まで）",
    closedDays: "毎週月曜日（祝日の場合は翌平日）、年末年始",
    admission: "大人500円、中学生以下無料",
    website: "https://www.tennojizoo.jp/",
    features: ["アフリカサバンナ", "大型類人猿", "夜行性動物館"],
  },
  {
    id: "ikeda-zoo",
    name: "池田市立こども動物園",
    nameKana: "いけだしりつこどもどうぶつえん",
    prefecture: "osaka",
    address: "大阪府池田市綾羽2-5-33",
    lat: 34.8168,
    lon: 135.4316,
    openingHours: "9:00〜17:00（入園は16:30まで）",
    closedDays: "毎週火曜日（祝日の場合は翌平日）、年末年始",
    admission: "無料",
    website: "https://www.city.ikeda.osaka.jp/",
    features: ["ポニー乗馬", "ふれあいコーナー"],
  },
  {
    id: "kyoto-zoo",
    name: "京都市動物園",
    nameKana: "きょうとしどうぶつえん",
    prefecture: "kyoto",
    address: "京都府京都市左京区岡崎法勝寺町岡崎公園内",
    lat: 35.0142,
    lon: 135.7826,
    openingHours: "9:00〜17:00（入園は16:00まで）",
    closedDays: "毎週月曜日（祝日の場合は翌平日）、年末年始",
    admission: "大人750円、中学生以下無料",
    website: "https://www5.city.kyoto.jp/zoo/",
    features: ["ゴリラ", "ニシローランドゴリラ", "もぐもぐタイム"],
  },
  {
    id: "kobe-oji-zoo",
    name: "神戸市立王子動物園",
    nameKana: "こうべしりつおうじどうぶつえん",
    prefecture: "hyogo",
    address: "兵庫県神戸市灘区王子町3-1",
    lat: 34.7126,
    lon: 135.2019,
    openingHours: "9:00〜17:00（入園は16:30まで）",
    closedDays: "毎週水曜日（祝日の場合は翌平日）、年末年始",
    admission: "大人600円、中学生以下無料",
    website: "https://www.city.kobe.lg.jp/oji-zoo/",
    features: ["ジャイアントパンダ", "コアラ", "ナイトズー（夏季）"],
  },
  {
    id: "himeji-zoo",
    name: "姫路市立動物園",
    nameKana: "ひめじしりつどうぶつえん",
    prefecture: "hyogo",
    address: "兵庫県姫路市本町68姫路城内",
    lat: 34.8418,
    lon: 134.6949,
    openingHours: "9:00〜17:00（入園は16:30まで）",
    closedDays: "年末年始",
    admission: "大人210円、中学生以下無料",
    website: "https://www.city.himeji.lg.jp/zoo/",
    features: ["チンパンジー", "ホワイトライオン", "姫路城隣接"],
  },
  {
    id: "awaji-farm-park",
    name: "淡路ファームパーク イングランドの丘",
    nameKana: "あわじふぁーむぱーく いんぐらんどのおか",
    prefecture: "hyogo",
    address: "兵庫県南あわじ市八木養宜上1401",
    lat: 34.2894,
    lon: 134.8206,
    openingHours: "9:30〜17:00（季節により変動）",
    closedDays: "年中無休（悪天候を除く）",
    admission: "大人1,600円、小中学生900円",
    website: "https://www.england-hill.com/",
    features: ["コアラ", "羊の放牧", "淡路島"],
  },
  {
    id: "nara-koen-deer",
    name: "奈良公園（シカ）",
    nameKana: "ならこうえん（しか）",
    prefecture: "nara",
    address: "奈良県奈良市雑司町469",
    lat: 34.6853,
    lon: 135.8449,
    openingHours: "終日開放",
    closedDays: "なし",
    admission: "無料（鹿せんべい販売あり）",
    website: "https://www.pref.nara.jp/1708.htm",
    features: ["野生のシカ", "世界遺産", "東大寺隣接"],
  },
  {
    id: "adventure-world",
    name: "アドベンチャーワールド",
    nameKana: "あどべんちゃーわーるど",
    prefecture: "wakayama",
    address: "和歌山県西牟婁郡白浜町堅田2399",
    lat: 33.6858,
    lon: 135.3555,
    openingHours: "10:00〜17:00（季節により変動）",
    closedDays: "不定休（公式サイト参照）",
    admission: "大人5,000円、中学生3,800円、小学生3,200円",
    website: "https://www.aws-s.com/",
    features: ["ジャイアントパンダ", "サファリワールド", "イルカショー"],
  },
  {
    id: "wakayama-castle-zoo",
    name: "和歌山城動物園",
    nameKana: "わかやまじょうどうぶつえん",
    prefecture: "wakayama",
    address: "和歌山県和歌山市一番丁3",
    lat: 34.2302,
    lon: 135.1722,
    openingHours: "9:00〜17:30",
    closedDays: "12月29日〜1月1日",
    admission: "無料",
    website: "https://www.city.wakayama.wakayama.jp/",
    features: ["白いライオン", "白いトラ", "和歌山城隣接"],
  },
];
