// Generated by scripts/sync-jaza-members.mjs. Do not edit manually.

export interface JazaMemberFacility {
  name: string;
  website: string;
}

export const JAZA_MEMBER_SOURCE_URL = "https://www.jaza.jp/search-enkan";

export const JAZA_KINKI_ZOOS: JazaMemberFacility[] = [
  {
    "name": "京都動物園",
    "website": "https://zoo.city.kyoto.lg.jp/zoo/"
  },
  {
    "name": "ごかつら池どうぶつパーク",
    "website": "https://gokatsura.jp/"
  },
  {
    "name": "和歌山城公園",
    "website": "http://wakayamajo.jp/animal/index.html"
  },
  {
    "name": "アドベンチャーワールド",
    "website": "http://aws-s.com/"
  },
  {
    "name": "天王寺動物園",
    "website": "https://www.tennojizoo.jp/"
  },
  {
    "name": "五月山動物園",
    "website": "http://www.satsukiyamazoo.com/"
  },
  {
    "name": "王子動物園",
    "website": "http://www.kobe-ojizoo.jp/"
  },
  {
    "name": "神戸どうぶつ王国",
    "website": "http://www.kobe-oukoku.com/"
  },
  {
    "name": "姫路動物園",
    "website": "http://www.city.himeji.lg.jp/dobutuen"
  },
  {
    "name": "姫路セントラルパーク",
    "website": "http://www.central-park.co.jp/"
  },
  {
    "name": "淡路ファームパーク",
    "website": "http://www.england-hill.com/"
  }
];

export const JAZA_KINKI_AQUARIUMS: JazaMemberFacility[] = [
  {
    "name": "琵琶湖博物館",
    "website": "http://www.biwahaku.jp/"
  },
  {
    "name": "京都水族館",
    "website": "http://www.kyoto-aquarium.com/"
  },
  {
    "name": "鳥羽水族館",
    "website": "http://www.aquarium.co.jp/"
  },
  {
    "name": "伊勢シーパラダイス",
    "website": "https://ise-seaparadise.com/"
  },
  {
    "name": "海遊館",
    "website": "http://www.kaiyukan.com/index.html"
  },
  {
    "name": "NIFREL",
    "website": "https://www.nifrel.jp/"
  },
  {
    "name": "神戸須磨シーワールド",
    "website": "https://kobe-sumasui.jp/"
  },
  {
    "name": "AQUARIUM×ART átoa",
    "website": "https://atoa-kobe.jp/"
  },
  {
    "name": "城崎マリンワールド",
    "website": "http://marineworld.hiyoriyama.co.jp/"
  },
  {
    "name": "姫路水族館",
    "website": "http://www.city.himeji.lg.jp//aqua/"
  }
];
